apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-mhp-pvc
  namespace: minio
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi