apiVersion: apps/v1
kind: Deployment
metadata:
  name: knote
  namespace: knote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knote
  template:
    metadata:
      labels:
        app: knote
    spec:
      containers:
        - name: app
          image: donb4iu/knote-java:1.0.1
          resources:
            requests:
              cpu: "200m"    # Set the CPU request (200 milliCPU in this case)
            limits:
              cpu: "500m"    # Optional: Set a CPU limit if needed
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
## Not necessary with multi arc image
#      nodeSelector:
#        kubernetes.io/arch: arm64
---
apiVersion: v1
kind: Service
metadata:
  name: knote
  namespace: knote
spec:
  selector:
    app: knote
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
