apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-scaler-binding
  namespace: knote
subjects:
  - kind: ServiceAccount
    name: default
    namespace: knote
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deployment-scaler
