apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-up
  namespace: knote
spec:
  schedule: "30 13 * * *"  # 8:30 AM every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scale-up
            image: bitnami/kubectl:latest
            command:
              - kubectl
              - scale -n knote
              - deployment/knote
              - --replicas=2
#            env:
#              - name: KUBERNETES_SERVICE_HOST
#                value: "https://kubernetes.default.svc"
#              - name: KUBERNETES_SERVICE_PORT
#                value: "443"
          restartPolicy: OnFailure