apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-down
  namespace: knote
spec:
  schedule: "30 5 * * *"  # 12:30 AM every day
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1 # Retain after successful completion
  failedJobsHistoryLimit: 1 # Retain failed so that we see it
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scale-down
            image: bitnami/kubectl:latest
            command:
              - kubectl
              - scale
              - -n 
              - knote
              - deployment/knote
              - --replicas=1
#            env:
#              - name: KUBERNETES_SERVICE_HOST
#                value: "https://kubernetes.default.svc"
#              - name: KUBERNETES_SERVICE_PORT
#                value: "443"
          restartPolicy: OnFailure