apiVersion: http.crossplane.io/v1alpha2
kind: DisposableRequest
metadata:
  name: slack-webhook-creation-$podName
spec:
  deletionPolicy: Orphan
  forProvider:
    url: $WEBHOOK_URL
    method: POST
    body: {
      "channel": "#kalaxy2",
      "username": "donb4iu",
      "text": "test",
      "icon_emoji": ":ghost:",
    }