apiVersion: v1
kind: Service
metadata:
  name: k8s-minio-console
  namespace: minio-operator
  labels:
    k8s-app: k8s-minio-console
spec:
  type: LoadBalancer
  selector:
    v1.min.io/tenant: microk8s
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 9090