apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: resume
  name: nginx
  namespace: resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      application: resume
  template:
    metadata:
      labels:
        app: nginx
        application: resume
    spec:
      containers:
      - name: nginx
        image: donb4iu/mynginx_resume:{{ .Values.env.APP_VERSION }}
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
## Not necessary with multi arc image
#      nodeSelector:
#        kubernetes.io/arch: arm64

