# pvc-nfs.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-storage
spec:
  storageClassName: nfs-csi-retain
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 6Gi