scrape_configs:
  - job_name: 'gpu'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: [‘nvidia-dcgm-exporter.gpu-operator-resources:9400']