apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: donb4iu/mynginx_resume:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
## Not necessary with multi arc image
#      nodeSelector:
#        kubernetes.io/arch: arm64

