apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: documentation
type: Opaque
data:
  webhook-url: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDA3Q0JSMjZXQUcvQjA3Q0hCMDlCRTMvamNhOGp2S2dmcXBVQzZJVHJ3bHI0Ukg1