name: Build Daux docs from markdown
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate static Daux files
      uses: addnab/docker-run-action@v3
      with:
        image: daux/daux.io:latest
        options: |
          --rm 
          -it
          -v ${{ github.workspace }}:/build
          -w /build
        run: echo "daux generate -s markdown -d docs"

    - name: Init new repo in dist folder and commit generated files
      run: |
        cd docs
        git init
        git add -A
        git config --local user.email "dbuddenbaum@gmail.com"
        git config --local user.name "donb4iu"
        git commit -m 'deploy'

    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.API_GITHUB_TOKEN }}
        branch: main
        force: true
        directory: ./docs
