name: Build Daux webpages from markdown, publish to donb4iu.github.io, push image to donb4iu/mynginx_docs:latest
on:
  push:
    branches: [ main ]
jobs:
  build:
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4

    - name: Generate Daux webpages
      uses: addnab/docker-run-action@v3
      id: generate_daux_webpages
      with:
        image: daux/daux.io:latest
        options: |
          --rm 
          -v ${{ github.workspace }}:/build
          -w /build
        run: /daux/bin/daux generate -s markdown -d docs

    - name: commit generated webpages files
      run: |
        git config --local user.email "dbuddenbaum@gmail.com"
        git config --local user.name "donb4iu"
        git add -A
        git commit -a -m 'commit generated daux.io generated docs to repository'

    - name: Force push generated webpages back to the docs directory
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: main

    - name: Publish webpages to donb4iu.github.io
      uses: cpina/github-action-push-to-another-repository@main
      id: publish_webpages_to_gitpages
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'docs'
        target-directory: 'docs'
        destination-github-username: 'donb4iu'
        destination-repository-name: 'donb4iu.github.io'
        target-branch: 'main'
        commit-message: 'DauxIO webpage commit from Kalaxy2'
        user-email: dbuddenbaum@gmail.com

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push image to donb4iu/mynginx_docs:latest
      uses: docker/build-push-action@v6
      id: build_and_push_image_to_dockerhub
      with:
          platforms: linux/amd64,linux/arm64
          file: yaml/nginx-docs/k8s-doc-to-nginx/nginx/Dockerfile          
          push: true
          tags: donb4iu/mynginx_docs:latest
    
    - name: Send Slack message
      uses: keithalpichi/slack-action@0.0.6
      with:
          template: steps1
          description: Build Daux webpages from markdown, push to docs/gitpages, then cr8 and push donb4iu/mynginx_docs:latest
          title: Kalaxy2 documentation Build
          status: ${{ toJSON(steps.generate_daux_webpages), toJSON(steps.build_and_push_image_to_dockerhub), toJSON(steps.build_and_push_image_to_dockerhub) }}
