name: Build Daux docs from markdown
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4

    - name: Generate static Daux files
      uses: addnab/docker-run-action@v3
      with:
        image: daux/daux.io:latest
        options: |
          --rm 
          -it
          -v ${{ github.workspace }}:/build
          -w /build
        shell: bash
        run: daux generate -s markdown -d docs

    - name: commit generated files
      run: |
        git config --local user.email "dbuddenbaum@gmail.com"
        git config --local user.name "donb4iu"
        git add -A
        git commit -a -m 'commit generated daux.io generated docs to repository'

    - name: Force push to destination branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: main
