name: Deploy Daux docs to pages
on:
  push:
    branches:
    - main

jobs:
  publish: 
    runs-on: ubuntu-latest
    steps:
    - name: Push generated webpage to another repository
      uses: nkoppel/push-files-to-another-repository@v1.1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-files: 'docs/'
        destination-username: 'donb4iu'
        destination-repository: 'donb4iu.github.io'
        destination-branch: 'main'
        destination-directory: 'docs/'
        commit-email: 'dbuddenbaum@gmail.com'
