apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: attendlytical
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: cheahwen/attendlytical-client:latest
        imagePullPolicy: Always # Change to Never if using local Docker image
        ports:
        - containerPort: 3000 #  Need to be same as target port in service
        env:
        - name: REACT_APP_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: client-config
              key: base-url
        resources:
          limits:
            cpu: 600m
            memory: 4Gi
          requests:
            cpu: 300m
            memory: 2Gi
      nodeSelector:
          kubernetes.io/arch: amd64
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: attendlytical
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 3000  # Service running port (minikube tunnel will proxy this port)
      targetPort: 3000 # Need to be same as container port in deployment